package com.FMS.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;
@Getter
public enum ErrorCode {
    USER_NOT_FOUND(1001, "User not found", HttpStatus.NOT_FOUND),
    USER_ALREADY_EXISTS(1002, "User already exists", HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED(1003, "Unauthenticated", HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED(1004, "Access denied", HttpStatus.FORBIDDEN),
    VEHICLE_ALREADY_EXISTS(1005, "Vehicle already exists", HttpStatus.BAD_REQUEST),
    VEHICLE_NOT_FOUND(1006, "Vehicle not found", HttpStatus.NOT_FOUND),
    INVALID_KEY(9999, "Invalid key", HttpStatus.BAD_REQUEST),
    DRIVER_NOT_FOUND(1007, "Driver not found", HttpStatus.NOT_FOUND),
    DRIVER_HAS_ACTIVE_TRIP(1008, "Driver already has active or scheduled trip", HttpStatus.BAD_REQUEST),
    TRIP_NOT_FOUND(1009, "Trip not found", HttpStatus.NOT_FOUND),
    MAINTENANCE_NOT_FOUND(1010, "Maintenance not found", HttpStatus.NOT_FOUND),
    INVOICE_NOT_FOUND(1011, "Invoice not found", HttpStatus.NOT_FOUND),
    INVOICE_CANCELLED(1012, "Invoice cancelled", HttpStatus.BAD_REQUEST),
    INVALID_INVOICE_STATUS(1013, "Invalid invoice status", HttpStatus.BAD_REQUEST),
    EXPENSE_NOT_FOUND(1014, "Expense not found", HttpStatus.NOT_FOUND),
    DRIVER_ALREADY_EXISTS(1015, "Driver already exists", HttpStatus.BAD_REQUEST),
    CUSTOMER_NOT_FOUND(1016, "Customer not found", HttpStatus.NOT_FOUND),
    CONTRACT_NOT_FOUND(1017, "Contract not found", HttpStatus.NOT_FOUND),
    CONTRACT_CANNOT_CANCELLED(1018, "Completed contract cannot be cancelled", HttpStatus.BAD_REQUEST),
    CONTRACT_CANNOT_ACTIVATED(1019, "Only draft contract can be activated", HttpStatus.BAD_REQUEST),
    CONTRACT_CANNOT_COMPLETED(1020, "Only active contract can be completed", HttpStatus.BAD_REQUEST),
    TOKEN_EXPIRED(1021, "Token expired", HttpStatus.UNAUTHORIZED),
    INVALID_TOKEN(1022, "Invalid token", HttpStatus.UNAUTHORIZED),
    USER_DISABLED(1023, "User disabled", HttpStatus.FORBIDDEN),
    DRIVER_AGE_INVALID(1024, "Driver must be at least 18 years old", HttpStatus.BAD_REQUEST),
    INVALID_USERNAME(1025, "Username must be at least 6 characters", HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD(1026, "Password must be at least 8 characters", HttpStatus.BAD_REQUEST),
    CUSTOMER_ACCOUNT_ALREADY_LINKED(1027, "Customer account is already linked to another profile", HttpStatus.BAD_REQUEST),
    INVALID_CUSTOMER_ACCOUNT(1028, "User account must have CUSTOMER role", HttpStatus.BAD_REQUEST),
    INVOICE_ALREADY_EXISTS(1029, "Trip already has an invoice", HttpStatus.BAD_REQUEST),
    INVALID_MAINTENANCE_STATUS(1030, "Invalid maintenance status", HttpStatus.BAD_REQUEST),
    VEHICLE_NOT_AVAILABLE_FOR_MAINTENANCE(1031, "Vehicle is not available for maintenance", HttpStatus.BAD_REQUEST),
    VEHICLE_NOT_AVAILABLE(1032, "Vehicle is not available", HttpStatus.BAD_REQUEST),
    VEHICLE_HAS_ACTIVE_TRIP(1033, "Vehicle already has an active or scheduled trip", HttpStatus.BAD_REQUEST),
    TRIP_CANNOT_START(1034, "Only created trips can be started", HttpStatus.BAD_REQUEST),
    TRIP_CANNOT_COMPLETE(1035, "Only in-progress trips can be completed", HttpStatus.BAD_REQUEST),
    TRIP_CANNOT_CANCEL(1036, "Completed or cancelled trips cannot be cancelled", HttpStatus.BAD_REQUEST),
    CONTRACT_ALREADY_EXISTS(1037, "Contract code already exists", HttpStatus.BAD_REQUEST),
    INVALID_TRIP_TIME(1038, "Trip start time must be before end time", HttpStatus.BAD_REQUEST),
    INVALID_FREIGHT_INPUT(1039, "Distance, cargo weight and freight rate must be greater than 0", HttpStatus.BAD_REQUEST),
    INVALID_INVOICE_AMOUNT(1040, "Invoice amount is required", HttpStatus.BAD_REQUEST),
    TRIP_NOT_COMPLETED(1041, "Trip must be completed before creating invoice", HttpStatus.BAD_REQUEST),
    INVALID_ROUTE_ADDRESS(1042, "Start and end locations are required", HttpStatus.BAD_REQUEST),
    ROUTE_DISTANCE_UNAVAILABLE(1043, "Unable to calculate route distance", HttpStatus.BAD_REQUEST),
    INVALID_REPORT_PERIOD(1044, "Report start date must not be after end date", HttpStatus.BAD_REQUEST),
    INVALID_EMPLOYEE_INPUT(1045, "Employee information is incomplete or invalid", HttpStatus.BAD_REQUEST),
    EMPLOYEE_CODE_ALREADY_EXISTS(1046, "Employee code already exists", HttpStatus.BAD_REQUEST),
    INVALID_EMPLOYEE_ROLE(1047, "Employee role must be MANAGER or ACCOUNTANT", HttpStatus.BAD_REQUEST),
    INVALID_CUSTOMER_REGISTRATION(1048, "Customer name and phone are required", HttpStatus.BAD_REQUEST),
    INVALID_AVATAR(1049, "Avatar must be an image smaller than 1.5 MB", HttpStatus.BAD_REQUEST),
    VEHICLE_STATUS_MANAGED(1050, "Running and maintenance statuses are updated by their own workflows", HttpStatus.BAD_REQUEST),
    DELETE_BLOCKED_BY_RELATED_DATA(1051, "This record cannot be deleted because related data exists", HttpStatus.CONFLICT),
    PAID_INVOICE_CANNOT_DELETE(1052, "Paid invoice cannot be deleted", HttpStatus.BAD_REQUEST),
    INVALID_DEPOSIT_POLICY(1053, "Deposit policy is incomplete or invalid", HttpStatus.BAD_REQUEST),
    DEPOSIT_NOT_FOUND(1054, "Deposit receipt not found", HttpStatus.NOT_FOUND),
    INVALID_DEPOSIT_AMOUNT(1055, "Deposit amount must be greater than 0 and within the available balance", HttpStatus.BAD_REQUEST),
    DEPOSIT_REFUND_EXCEEDS_AVAILABLE(1056, "Refund amount exceeds the available deposit balance", HttpStatus.BAD_REQUEST),
    DEPOSIT_TARGET_MISMATCH(1057, "Deposit customer, contract and trip do not match", HttpStatus.BAD_REQUEST),
    DEPOSIT_RECEIPT_ALREADY_EXISTS(1058, "Deposit receipt number already exists", HttpStatus.BAD_REQUEST),
    DEPOSIT_CANNOT_DELETE(1059, "Allocated or refunded deposit receipts cannot be deleted", HttpStatus.CONFLICT),
    INVALID_DEPOSIT_DATE(1060, "Deposit and refund dates must be valid and must not be in the future", HttpStatus.BAD_REQUEST),
    INVALID_PAYMENT_METHOD(1061, "Payment method is required", HttpStatus.BAD_REQUEST),
    INVALID_PAYMENT_DATE(1062, "Payment date must be between the invoice issue date and today", HttpStatus.BAD_REQUEST),
    BANK_TRANSFER_DETAILS_REQUIRED(1063, "Bank name and transaction reference are required for bank transfer", HttpStatus.BAD_REQUEST),
    INVOICE_ALREADY_PAID(1064, "Invoice has already been paid", HttpStatus.BAD_REQUEST),
    INVALID_CONTRACT_DATE(1065, "Contract dates must satisfy signed date <= start date <= end date", HttpStatus.BAD_REQUEST),
    CONTRACT_NOT_ACTIVE(1066, "Only active contracts can be used for trips", HttpStatus.BAD_REQUEST),
    CONTRACT_CUSTOMER_MISMATCH(1067, "Trip customer does not match contract customer", HttpStatus.BAD_REQUEST),
    CONTRACT_OUTSIDE_VALIDITY(1068, "Trip schedule is outside the contract validity period", HttpStatus.BAD_REQUEST),
    CONTRACT_HAS_OPEN_TRIPS(1069, "Contract still has created, assigned or in-progress trips", HttpStatus.CONFLICT),
    CONTRACT_CANNOT_EDIT(1070, "Only draft contracts can be edited", HttpStatus.BAD_REQUEST),
    REQUIRED_DEPOSIT_NOT_RECEIVED(1071, "Required deposit must be received before starting the trip", HttpStatus.BAD_REQUEST),
    INVALID_MAINTENANCE_DATE(1072, "Maintenance dates are invalid", HttpStatus.BAD_REQUEST),
    MAINTENANCE_NOT_DUE(1073, "Scheduled maintenance cannot start before its maintenance date", HttpStatus.BAD_REQUEST),
    MAINTENANCE_CANNOT_DELETE(1074, "Only pending or cancelled maintenance records can be deleted", HttpStatus.CONFLICT),
    INVALID_INVOICE_DATE(1075, "Invoice issue date and due date are invalid", HttpStatus.BAD_REQUEST),
    TRIP_CANNOT_EDIT(1076, "Only created or assigned trips can be edited", HttpStatus.BAD_REQUEST),
    CONTRACT_CANNOT_DELETE(1077, "Only draft or cancelled contracts can be deleted", HttpStatus.CONFLICT),
    INVALID_PERSON_NAME(1078, "Họ tên phải có từ 2 đến 100 ký tự", HttpStatus.BAD_REQUEST),
    INVALID_PHONE(1079, "Số điện thoại không đúng định dạng Việt Nam", HttpStatus.BAD_REQUEST),
    INVALID_ID_NUMBER(1080, "CCCD, CMND hoặc mã số thuế không đúng định dạng", HttpStatus.BAD_REQUEST),
    INVALID_DATE_OF_BIRTH(1081, "Ngày sinh là bắt buộc và phải là ngày trong quá khứ", HttpStatus.BAD_REQUEST),
    INVALID_EMAIL(1082, "Email không đúng định dạng", HttpStatus.BAD_REQUEST),
    INVALID_ADDRESS(1083, "Địa chỉ phải có từ 5 đến 255 ký tự", HttpStatus.BAD_REQUEST),
    INVALID_DRIVER_LICENSE(1084, "Thông tin giấy phép lái xe không đầy đủ hoặc không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_EMPLOYEE_DATE(1085, "Nhân viên phải đủ 18 tuổi và ngày vào làm không được ở tương lai", HttpStatus.BAD_REQUEST),
    INVALID_VEHICLE_INPUT(1086, "Thông tin phương tiện không đầy đủ hoặc không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_EXPENSE_INPUT(1087, "Số tiền chi phải lớn hơn 0 và ngày chi không được ở tương lai", HttpStatus.BAD_REQUEST),
    INVALID_CONTRACT_INPUT(1088, "Thông tin hợp đồng không đầy đủ hoặc không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_MAINTENANCE_INPUT(1089, "Thông tin bảo dưỡng không đầy đủ hoặc không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_INVOICE_INPUT(1090, "Thông tin hóa đơn không đầy đủ hoặc không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_REQUEST_FORMAT(1091, "Dữ liệu không đúng định dạng; hãy kiểm tra ngày, số và giá trị đã chọn", HttpStatus.BAD_REQUEST),
    INVALID_AUTH_REQUEST(1092, "Tên đăng nhập và mật khẩu là bắt buộc", HttpStatus.BAD_REQUEST),
    DRIVER_LICENSE_EXPIRED(1093, "Giấy phép lái xe không còn hiệu lực trong thời gian chuyến", HttpStatus.BAD_REQUEST),
    VEHICLE_CAPACITY_EXCEEDED(1094, "Trọng lượng hàng vượt tải trọng phương tiện", HttpStatus.BAD_REQUEST),
    TRIP_START_TOO_EARLY(1095, "Chưa đến thời điểm được phép bắt đầu chuyến", HttpStatus.BAD_REQUEST),
    TRIP_START_WINDOW_EXPIRED(1096, "Chuyến đã quá thời gian dự kiến và không thể bắt đầu", HttpStatus.BAD_REQUEST),
    EXPENSE_TRIP_ACCESS_DENIED(1097, "Tài xế chỉ được ghi và xem chi phí của chuyến được phân công", HttpStatus.FORBIDDEN),
    EXPENSE_TRIP_STATUS_INVALID(1098, "Chỉ được ghi chi phí khi chuyến đang vận chuyển hoặc đã hoàn tất", HttpStatus.BAD_REQUEST),
    EXPENSE_DATE_OUTSIDE_TRIP(1099, "Ngày chi phải nằm trong thời gian thực hiện chuyến", HttpStatus.BAD_REQUEST),
    EXPENSE_ALREADY_REVIEWED(1100, "Khoản chi này đã được duyệt hoặc từ chối", HttpStatus.CONFLICT),
    EXPENSE_REJECTION_NOTE_REQUIRED(1101, "Cần nhập lý do khi từ chối khoản chi", HttpStatus.BAD_REQUEST),
    INVALID_EXPENSE_RECEIPT(1102, "Ảnh biên lai phải là JPG, PNG hoặc WebP và không vượt quá 1.5 MB", HttpStatus.BAD_REQUEST),
    DRIVER_ACCOUNT_ALREADY_LINKED(1103, "Tài xế đã có tài khoản đăng nhập", HttpStatus.CONFLICT),
    DRIVER_ACCOUNT_NOT_LINKED(1104, "Tài xế chưa được cấp tài khoản đăng nhập", HttpStatus.NOT_FOUND),
    INVALID_DRIVER_ACCOUNT(1105, "Tài khoản liên kết không phải tài khoản tài xế", HttpStatus.BAD_REQUEST),
    PASSWORD_CHANGE_REQUIRED(1106, "Bạn phải đổi mật khẩu tạm trước khi sử dụng hệ thống", HttpStatus.FORBIDDEN),
    INVALID_CURRENT_PASSWORD(1107, "Mật khẩu hiện tại không đúng", HttpStatus.BAD_REQUEST),
    NEW_PASSWORD_MUST_DIFFER(1108, "Mật khẩu mới phải khác mật khẩu hiện tại", HttpStatus.BAD_REQUEST)
    ;
    private int code;
    private String message;
    private HttpStatusCode statusCode;

    ErrorCode(int code, String message, HttpStatusCode statusCode) {
        this.code = code;
        this.message = message;
        this.statusCode = statusCode;
    }
}
