ALTER TABLE trips
    ADD COLUMN IF NOT EXISTS cargo_weight_ton DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS freight_rate_per_ton_km DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS freight_amount DOUBLE PRECISION;
