ALTER TABLE users
    ADD COLUMN IF NOT EXISTS employee_code VARCHAR(100),
    ADD COLUMN IF NOT EXISTS full_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS address VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS id_number VARCHAR(100),
    ADD COLUMN IF NOT EXISTS dob DATE,
    ADD COLUMN IF NOT EXISTS gender VARCHAR(20),
    ADD COLUMN IF NOT EXISTS position VARCHAR(255),
    ADD COLUMN IF NOT EXISTS hire_date DATE,
    ADD COLUMN IF NOT EXISTS avatar_url TEXT,
    ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;

UPDATE users
SET active = TRUE
WHERE active IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_users_employee_code
    ON users (employee_code)
    WHERE employee_code IS NOT NULL;
